### ISSUE TITLE
Serial number

### ISSUE THREAD

**Issue by LinkTed** [wisespace-io/yubico-rs#10]
How do I get the serial number from the yubikey?

**Comment by wisespace-io** [comment]
I thought it would be enough to expose the serial number in the Device Structure. There is a field serial number returned, you can verify if you print the device descriptor println!("{:?}", descr);  inside the if below

https://github.com/wisespace-io/yubico-rs/blob/master/src/lib.rs#L104

However, apparently it requires to implement a new method to retrieve this information.

https://github.com/Yubico/python-yubico/blob/a72e8eddb90da6ee96e29f60912ca1f2872c9aea/yubico/yubikey_usb_hid.py#L479

**Comment by wisespace-io** [comment]
Ok, it seems that it is also possible using the libusb, it would need to open the device and read the information https://github.com/dcuddeback/libusb-rs/blob/master/examples/list_devices.rs#L27

See https://github.com/dcuddeback/libusb-rs/blob/master/examples/list_devices.rs#L92

**Comment by LinkTed** [comment]
I mean the serial number from the yubico personalization tool.
![screenshot_25 05 2019-18:04:49](https://user-images.githubusercontent.com/6806266/58372024-c229b780-7f17-11e9-8913-560eb86e150b.png)

**Comment by wisespace-io** [comment]
Yes, I know. We have two options as described above. I will implement one of them during the week.

**Comment by LinkTed** [comment]
I'm sorry to bother you, do you know when it will be implemented?

**Comment by wisespace-io** [comment]
@LinkTed I tried via libusb but the serial number information was empty. I will try the second option as soon as I have some time.

**Comment by LinkTed** [comment]
Okay, I will wait. Thank you.

**Comment by wisespace-io** [comment]
@LinkTed Implemented. Could you confirm that it works? See the example below

https://github.com/wisespace-io/yubico-rs/blob/master/examples/serial_number.rs

**Comment by LinkTed** [comment]
I cannot compile the new crate.
First I get this error:
```
  --> /home/linkted/.cargo/registry/src/github.com-1ecc6299db9ec823/yubico-0.6.0/src/lib.rs:19:1
   |
19 | extern crate futures;
   | ^^^^^^^^^^^^^^^^^^^^^ can't find crate
```
To fix it you have to add the features `futures` in the `Cargo.toml` file, for example:
```
...
features = ["futures"]
...
```
Maybe you have forget to add a `#[cfg(feature = "futures")]`.
And then I get the following error:
```
error[E0277]: `yubicoerror::YubicoError` doesn't implement `std::fmt::Display`
  --> /home/linkted/.cargo/registry/src/github.com-1ecc6299db9ec823/yubico-0.6.0/src/yubicoerror.rs:95:6
   |
95 | impl error::Error for YubicoError {
   |      ^^^^^^^^^^^^ `yubicoerror::YubicoError` cannot be formatted with the default formatter
   |
   = help: the trait `std::fmt::Display` is not implemented for `yubicoerror::YubicoError`
   = note: in format strings you may be able to use `{:?}` (or {:#?} for pretty-print) instead
```

**Comment by wisespace-io** [comment]
@LinkTed I just cloned the repository and ran the example:

flavio@dev:~/development/temp/yubico-rs$ cargo run --release --example "serial_number"
   Compiling hex v0.3.2
   Compiling yubico v0.6.0 (/home/flavio/development/temp/yubico-rs)
    Finished release [optimized] target(s) in 4.01s
     Running `target/release/examples/serial_number`

Could you clone it in a different directory and run the command below?

cargo run --release --example "serial_number"

**Comment by LinkTed** [comment]
Okay it worked with my Yubikey.

**Comment by wisespace-io** [comment]
@LinkTed Do you have problems using the crate in your project? As we added conditional compilation to sync/async (futures), we may have introduced a bug.

**Comment by netmiller** [comment]
I'm totally newbie in Rust, sorry!  But I am working with Yubikeys with other env's (node,golang). This lib is very interesting, so I decided to give it a try, but getting errors :

````
► iMac@yubico-rs$ cargo run --release --example "serial_number"
    Finished release [optimized] target(s) in 0.24s
     Running `target/release/examples/serial_number`
Vendor ID: 4176 Product ID 1031
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Access', src/libcore/result.rs:997:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
````

and : 

````
 ► iMac@yubico-rs$ RUST_BACKTRACE=1 cargo run --release --example "serial_number"
    Finished release [optimized] target(s) in 0.20s
     Running `target/release/examples/serial_number`
Vendor ID: 4176 Product ID 1031
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Access', src/libcore/result.rs:997:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
   1: std::sys_common::backtrace::_print
   2: std::panicking::default_hook::{{closure}}
   3: std::panicking::default_hook
   4: std::panicking::rust_panic_with_hook
   5: std::panicking::continue_panic_fmt
   6: rust_begin_unwind
   7: core::panicking::panic_fmt
   8: core::result::unwrap_failed
   9: yubico::manager::open_device
  10: yubico::Yubico::read_serial_number
  11: serial_number::main
  12: std::rt::lang_start::{{closure}}
  13: std::panicking::try::do_call
  14: __rust_maybe_catch_panic
  15: std::rt::lang_start_internal
  16: main
► iMac@yubico-rs$
````
Maybe it is some bugs in my dev.env; I installed **rustup** just for this, and haven't used it before ?

**Comment by wisespace-io** [comment]
@netmiller Which Yubikey do you have (I have Yubikey 4)? 

https://support.yubico.com/support/solutions/articles/15000006486-yubikey-4

Read the serial number was introduced in YubiKey 2.2, unfortunately the crate does not check the version yet to proper error handling. It might be the reason for the error above.

https://github.com/wisespace-io/yubico-rs/blob/master/src/manager.rs#L60

I need to store the version to and return an unsupported error message if the version is < 2.2, if you add the line below, it should print the version

    println!("{:?}.{:?}.{:?}", buf[1], buf[2], buf[3]);

**Comment by netmiller** [comment]
@wisespace-io : I have tried 3 Yubikeys:

- Yubikey5 : firmware 5.2.2 (ordered 2~3 weeks ago, so they are brand new)
- Yubikey5: firmware 5.1.1 (ordered about January 2019)
- Yubikey4: firmware 4.3.7 (ordered about March 2018)

All of them raise same error .

Here is some info about newest YUbikey :

````
► iMac@client$ ykinfo -a
serial: 10142622
serial_hex: 9ac39e
serial_modhex: klreku
version: 5.1.2
touch_level: 1285
programming_sequence: 1
slot1_status: 1
slot2_status: 0
vendor_id: 1050
product_id: 407
````

I'm almost sure they are version 2.2 (at least). Where can I found more info about version?

**Comment by netmiller** [comment]
Here is **ykinfo -a** from my oldest key :

````
► iMac@client$ ykinfo -a
serial: 7319308
serial_hex: 6faf0c
serial_modhex: hvlvcr
version: 4.3.7
touch_level: 517
programming_sequence: 1
slot1_status: 1
slot2_status: 0
vendor_id: 1050
product_id: 407
````

**Comment by wisespace-io** [comment]
@netmiller I improved the error handling to see if it can help to identify the problem. Could you pull the latest? Apparently the error happens when it tries to open the device, maybe the applications does not have permission to open the usb device, but it may be something else.

**Comment by netmiller** [comment]
@wisespace-io  Yes, it is working now!  I thought you have improved only error handling to see more information, but you have fixed it :)  All my 3 yubikeys are working now.

````
$ RUST_BACKTRACE=1 cargo run --release --example "serial_number"
   Compiling yubico v0.6.1 (/Users/esa/devel/rust/yubico-rs)
    Finished release [optimized] target(s) in 3.73s
     Running `target/release/examples/serial_number`
Vendor ID: 4176 Product ID 1031
Serial Number 7319308

$ RUST_BACKTRACE=1 cargo run --release --example "serial_number"
    Finished release [optimized] target(s) in 0.20s
     Running `target/release/examples/serial_number`
Vendor ID: 4176 Product ID 1031
Serial Number 10142622

$ RUST_BACKTRACE=1 cargo run --release --example "serial_number"
    Finished release [optimized] target(s) in 0.19s
     Running `target/release/examples/serial_number`
Vendor ID: 4176 Product ID 1031
Serial Number 9027173

````

Thank you for your quick response !

**Comment by wisespace-io** [comment]
@netmiller Thank you for testing.
