### ISSUE TITLE
Conditional compilation vs multiple crates

### ISSUE THREAD

**Issue by pierre-l** [wisespace-io/yubico-rs#14]
Hi,

It appears I made a couple mistakes in my recent work on supporting asynchronous requests. I find it quite hard to maintain all the conditional compilation annotations across the whole crate. In the meantime, I think the USB use case and the online one are very different and I can hardly think of a use case for both at the same time. I would like to split the crate into these crates:

- yubico-core: shared code, crypto, etc.
- yubico-usb
- yubico-online

This would make it easier to segregate imports for both the crate developers and its users.

Would you agree with that?

**Comment by wisespace-io** [comment]
Yes, it sounds like a good idea. I thought to split sometime ago but I never had motivation. If you are willing to do it I can create the repos and give you access so we can split into these crates.

**Comment by pierre-l** [comment]
I was actually thinking about using a single repository for all the crates. I don't know publishing a crate works so I can't weigh down to pros and cons in the long term but at least for now this would be easier (+Git history).

I'll give it a try and keep you updated.

**Comment by wisespace-io** [comment]
@pierre-l When I first thought about split, I though to create two different repositories. Maybe it is the easiest way, so we would not need to have a yubico-core. I do not think yubico-online and yubico-usb share too much code. They would be complete different projects.

**Comment by pierre-l** [comment]
@wisespace-io Hi,
I gave it a try and you've very right about the amount of shared code. So I'm all for having 2 different repositories. Feel free to take a look and make any comment.

Do you want to conserve the "yubico" name? I used "yubico_online" for the OTP check, I'm not very inspired.

(and thanks for #13!)

**Comment by pierre-l** [comment]
Hi @wisespace-io ,

Do you still agree with that?
I'm someone who avoids taking additional responsibilities whenever I can, but I would understand if you'd rather have me take care of the online part. If that's the case please tell me, I'll fork this repo to host the online feature and write a PR to leave only the USB features here.

**Comment by wisespace-io** [comment]
Sorry for the delay, I just came back from my summer vacations. My suggestion is create a new repository just for the configuration and keep this one for the online part, so we do not need to rename it. If you are interested, I can add you as a co-maintainer of the online part.

The new repository https://github.com/wisespace-io/yubico-manager

**Comment by pierre-l** [comment]
Hi!
Really sorry about the delay, I've been quite overwhelmed the past couple of months.

Just to be sure I understand correctly: you suggest to move everything related to the USB features to the yubico-manager repo and keep everything related to online OTP validation in the current one?

**Comment by wisespace-io** [comment]
@pierre-l Yes, you got it :)

**Comment by wisespace-io** [comment]
@pierre-l Thank you again for the contribution. I added you to the authors list, please let me know if your name and email are correct

https://github.com/wisespace-io/yubico-rs/blob/master/Cargo.toml#L4

It will be displayed at the crate Authors Section https://crates.io/crates/yubico

**Comment by pierre-l** [comment]
@wisespace-io Perfect, thank you!
