### ISSUE TITLE
Allow usage of self-hosted OTP validation

### ISSUE THREAD

**Issue by lambdadog** [wisespace-io/yubico-rs#2]
Currently you just have the host boiled into the code, making it so people are required to be using the default yubico OTP validation server, but it's possible to host your own.

**Comment by wisespace-io** [comment]
@beta-phenylethylamine I see, I will try to implement.

**Comment by wisespace-io** [comment]
@beta-phenylethylamine I released a new version which allows to set custom API servers. Please, check and test if possible.

**Comment by lambdadog** [comment]
Sorry, I'm currently unable to test. I don't actually have a yubikey (yet). I found this repo doing research on them.
