### ISSUE TITLE
Breaking change in 0.9.2

### ISSUE THREAD

**Issue by gperinazzo** [wisespace-io/yubico-rs#23]
Hey folks,

The recently released version 0.9.2 contains a breaking change due to upgrading reqwest to 0.11. That version uses Tokio 1.0, making this crate no longer compatible with projects that still haven't migrated to Tokio 1.x.

This shows up as a runtime panic saying it could not find a Tokio 1.x executor running.

It may be a good idea to yank this version and release it as 0.10.

**Comment by wisespace-io** [comment]
@gperinazzo Sorry, it was my mistake. I just merged a PR from @pierre-l 
Released 0.10 and yanked 0.9.2
